version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app/src
    working_dir: /app/src
    command: >
      sh -c "yarn install && yarn dev"
volumes:
  database:
